### ISSUE TITLE
Exception has occurred: ModuleNotFoundError No module named 'web3'

### ISSUE THREAD

**Issue by Iliasrahmouni** [DefiDebauchery/discordpricebot#3]
I tried to install Web3 the proper way. did everything it needs. but i still get this error when i run tha main.py. Is there also any way to show us how to install the bot. Am kinda noob. thank you very much @DefiDebauchery

**Comment by DefiDebauchery** [comment]
What do you mean "the proper way" - Did you run `pip3 install -r requirements.txt` as listed in the README? That should install all of the pre-reqs.

**Comment by Iliasrahmouni** [comment]
yes i did run it previously and it was installed. But when i run the py i still get the error that No module named 'web3'. Please help... i am an admin in a discord in which i have to deliver a price bot for a bsc contract, i would really appreciate your help if u show me how to do it with your bot. Thank you very much

**Comment by DefiDebauchery** [comment]
It almost seems like you're not using the same pip and python versions somehow. Are you on an environment that has both python2 and python3, or python3.8 and python3.9? 

What's the output of `python3 --version` and `pip3 --version` ? (and are you using specifically `python3` to try and start the program?)

**Comment by Iliasrahmouni** [comment]
thats the output of the first command python3 --version: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases. 
but i do have python 3.9.5.

for the next command i have: pip 21.1.1.

and am running the programm with visual studio code.

**Comment by DefiDebauchery** [comment]
I see. Unfortunately this repo does assume that you're running on a proper server environment; I am unfamiliar with python on Windows, so I'm not certain where/how it is evaluating where packages are installed.

If you're able to install WSL (Windows Subsystem for Linux), this would allow you to run it with more certainty.

**Comment by Iliasrahmouni** [comment]
okay... and how can i give the program my bots token and everything cause i dont see where i can initiate my parameters so it can give me a price feedback only in the channel i want from the bot i want ?

**Comment by DefiDebauchery** [comment]
It's all in a config.yaml, which you copy from the example. Please re-review the README.
