### ISSUE TITLE
Price bot is not delivering anything in the chanel

### ISSUE THREAD

**Issue by Iliasrahmouni** [DefiDebauchery/discordpricebot#4]
I installed everything and followed the readme file and configured the config.yaml file by entering the api key and everything. I execute the code and nothing happens. The Bot is already in my server... How can i get the code to deliver me the price of my token ? Thanks for the code and for your help

**Comment by Iliasrahmouni** [comment]
when i execute in CMD i get the following error
![image](https://user-images.githubusercontent.com/51827091/118268476-b85f3d00-b4bd-11eb-8f65-0bd07b9e56fc.png)

**Comment by DefiDebauchery** [comment]
You guys gotta stop trying to force Python onto Windows :) Overall, you'll get better results by at least using WSL on your Windows install.

Although for this one, I'm not sure why you're passing the directory as an argument. You should be passing in the token ticker that you defined in `config.yaml` (see https://github.com/DefiDebauchery/discordpricebot/blob/main/config.yaml.example for tangible examples (though you'll have to update to the "v2" LPs for CAKE in that config - I'll update that in the example soon)

So it would be: `python main.py CAKE` (make sure that python executable is at least python 3.8)

**Comment by Iliasrahmouni** [comment]
i managed to fix all errors i had... i passed all arguments correctly i guess now. The bot goes online and shows some things please see the picture. I dont know why the bot is not sending any feeds, or how can i interact with it ??? Thanks for the help
![image](https://user-images.githubusercontent.com/51827091/118278567-6a9d0180-b4ca-11eb-9cf8-97cd306fc8fa.png)
![image](https://user-images.githubusercontent.com/51827091/118278620-7983b400-b4ca-11eb-97be-0011614295d4.png)

**Comment by DefiDebauchery** [comment]
Again, you did not read the README :(
You must use the checksum addresses (that is, the addresses with both upper and lowercase letters) for your tokens and contracts. 

You can find them on BSCScan. As an example, instead of the CAKE contract of `0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82`, you need to use `0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82`. 
This is a requirement from the web3.py library.
